### PR TITLE
Tracking for multiple pixels including typescript type definitions

### PR DESCRIPTION
**Pull request by mattgenious**
This adds jasondecastros support for tracking with multiple different pixel initialized as well as typescript typing for it.

### CODE REVIEW

**Comment by pesimeao** [comment]
Nice! @zsajjad can we merge this?

**Comment by tzarger** [comment]
Can this please be merged? @zsajjad

**Comment by Joeao** [comment]
Thanks for the updates @mattgenious. I made a small change in a separate pull request which is somewhat related to your Typescript maintenance https://github.com/zsajjad/react-facebook-pixel/pull/27

Hopefully they're both merged in the near future.

**Comment by mattgenious** [comment]
@Joeao ah I see, I missed that one 😄 yeah, lets hope they're merged soon 😁

**Comment by mpizarro03** [comment]
@zsajjad is this going to be merged any time soon?

**Comment by viktordineout** [comment]
Any news on this? Perhaps owner should invite more collaborators.

**Comment by mattgenious** [comment]
No news, I agree 😁

**Comment by zsajjad** [comment]
Has anyone tested it? I don't have enough time to test it and library doesn't have any tests :(

**Comment by zsajjad** [comment]
I have merged it by not publishing it until tested.

**Comment by mattgenious** [comment]
I will test it tomorrow, I have my own pull request running on a production system without problems, but I will clone the original repo with all changes and see if everything works or not.

**Comment by zsajjad** [comment]
Sounds good, let me know when you have tested it. I will release alpha soon and will test my self as well!

**Comment by zsajjad** [comment]
I have updated dependencies and also bumped new version hope this helps.

**Comment by mattgenious** [comment]
Hey @zsajjad I have tested and added some changes to the type definition that I will submit in a pull request that makes the types better correspond with the declared types from facebooks documentation here https://developers.facebook.com/docs/facebook-pixel/reference/#object-properties
Everything works for me with the changed types.

**Comment by mattgenious** [comment]
Also my apologies for the delay I got sick the day after 😬

**Pull request merged**
