### PR TITLE
autoConfig and debugging

### PR DESCRIPTION
**Pull request by michaelmitchell**
- syntax meets eslint-airbnb
- added option to set autoConfig
- added option to enable debug logging while in development

### CODE REVIEW

**Comment by zsajjad** [comment]
Thanks for the PR. I will test it soon and get back to you. One thing that i wish we can do here is removing this login part in `dist` file so there aren't any extra checks of debug in final bundle.

**Comment by michaelmitchell** [comment]
The problem with that is the npm package refers to the dist file so debugging would never be included. Overall I don't think you need to be using webpack and instead just regular a regular babel build to ./lib since most people using this plugin will be running their own webpack builds anyway like I am, you could still include a dist file for anyone including it directly by script tag and in there perhaps remove the option for debugging but an npm package without debugging is mostly useless to me.

**Comment by zsajjad** [comment]
For debugging of pixel, there is pixel chrome extension that shows all the event.

**Comment by michaelmitchell** [comment]
Yeah you can also pretty easily spot them in the Network tab just easier for me if I don't have to keep switching or use 3rd party extensions.

Completely up to you if you want to include it, I use react-ga which has similar logging and has been helpful, either way I published to a private npm package to use for now.

**Comment by chaddjohnson** [comment]
@zsajjad The ability to change `autoConfig` settings is pretty important. I recommend merging this.

**Pull request merged**
